INFO:root:('PLot cluster started: ', time.struct_time(tm_year=2020, tm_mon=5, tm_mday=2, tm_hour=12, tm_min=0, tm_sec=58, tm_wday=5, tm_yday=123, tm_isdst=1))
ERROR:root:Length of values does not match length of index
Traceback (most recent call last):
  File "plot_cluster.py", line 68, in <module>
    main()
  File "plot_cluster.py", line 61, in main
    run()
  File "plot_cluster.py", line 53, in run
    df["ground_truth"] = [target_names[l] for l in labels]
  File "/media/remote/tmandal/document-clustering-with-deep-neural-networks/code/.venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3487, in __setitem__
    self._set_item(key, value)
  File "/media/remote/tmandal/document-clustering-with-deep-neural-networks/code/.venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3564, in _set_item
    value = self._sanitize_column(key, value)
  File "/media/remote/tmandal/document-clustering-with-deep-neural-networks/code/.venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3749, in _sanitize_column
    value = sanitize_index(value, self.index, copy=False)
  File "/media/remote/tmandal/document-clustering-with-deep-neural-networks/code/.venv/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 612, in sanitize_index
    raise ValueError("Length of values does not match length of index")
ValueError: Length of values does not match length of index
INFO:root:Plot cluster ended: time.struct_time(tm_year=2020, tm_mon=5, tm_mday=2, tm_hour=12, tm_min=23, tm_sec=35, tm_wday=5, tm_yday=123, tm_isdst=1)
INFO:root:('Plot cluster', ' executed for 00:22:36.51')
